### ISSUE TITLE
upgrade to 8.0 seems to miss gem install

### ISSUE THREAD

**Issue by muelli** [debops/ansible-gitlab#27]
I tried to upgrade, but it failed with `/var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/spec_set.rb:92:in`block in materialize': Could not find CFPropertyList-2.3.1 in any of the sources (Bundler::GemNotFound) 

```
TASK: [debops.gitlab | Display deploy.html page] ****************************** 
ok: [default]

TASK: [debops.gitlab | Stop Sidekiq before upgrade] *************************** 
failed: [default] => {"changed": true, "cmd": "bundle exec rake sidekiq:stop RAILS_ENV=production", "delta": "0:00:00.359893", "end": "2015-09-25 12:24:08.907041", "rc": 1, "start": "2015-09-25 12:24:08.547148", "warnings": []}
stderr: /var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find CFPropertyList-2.3.1 in any of the sources (Bundler::GemNotFound)
    from /var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/spec_set.rb:85:in `map!'
    from /var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/spec_set.rb:85:in `materialize'
    from /var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/definition.rb:132:in `specs'
    from /var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/definition.rb:177:in `specs_for'
    from /var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/definition.rb:166:in `requested_specs'
    from /var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/environment.rb:18:in `requested_specs'
    from /var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/runtime.rb:13:in `setup'
    from /var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler.rb:122:in `setup'
    from /var/lib/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/setup.rb:18:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Running

```
git@debian-jessie-amd64-netboot:~/gitlab$ bundle exec rake sidekiq:stop RAILS_ENV=production
Could not find CFPropertyList-2.3.1 in any of the sources
Run `bundle install` to install missing gems.
git@debian-jessie-amd64-netboot:~/gitlab$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 10.4.2
Installing CFPropertyList 2.3.1
Using RedCloth 4.2.9
Using ace-rails-ap 2.0.1
Using i18n 0.7.0
Installing json 1.8.3
Installing minitest 5.7.0
Using thread_safe 0.3.5
...
...
...
Bundle complete! 153 Gemfile dependencies, 242 gems now installed.
Gems in the groups development, test, aws and postgres were not installed.
Bundled gems are installed into ./vendor/bundle.

```

installs many many gems.
Once it's finished, the task works fine.

I guess that you cannot use the rakefile when the dependencies are not met.
And the dependencies changed when the git repository was updated.
So I guess that a `when: git_update | changed`, then `gem install` is needed.

**Comment by bfabio** [comment]
@drybjed I think we can close this, we don't support 8.0 anymore.
