### ISSUE TITLE
Permission problems in a clean installation

### ISSUE THREAD

**Issue by pedroluislopez** [debops/ansible-gitlab#32]
In a clean installation /var/local/git/gitlab/log/unicorn.stderr.log log the following errors:

```
I, [2015-10-02T04:46:41.570908 #27653]  INFO -- : Refreshing Gem list
Rails Error: Unable to access log file. Please ensure that /var/local/git/gitlab/log/production.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:339:in `read': Permission denied @ rb_sysopen - /var/local/git/gitlab/config/secrets.yml (Errno::EACCES)
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:339:in `secrets'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'
    from /var/local/git/gitlab/config/initializers/secret_token.rb:33:in `<top (required)>'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `block in load'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:241:in `load'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:648:in `block in load_config_initializer'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/notifications.rb:161:in `instrument'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:647:in `load_config_initializer'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:611:in `each'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/engine.rb:611:in `block in <class:Engine>'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
    from /usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from /usr/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
    from /usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
    from /usr/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:44:in `each'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:44:in `tsort_each_child'
    from /usr/lib/ruby/2.1.0/tsort.rb:411:in `call'
    from /usr/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
    from /usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from /usr/lib/ruby/2.1.0/tsort.rb:345:in `each'
    from /usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
    from /usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
    from /usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
    from /usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'
    from /var/local/git/gitlab/config/environment.rb:5:in `<top (required)>'
    from config.ru:16:in `require'
    from config.ru:16:in `block in <main>'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
    from config.ru:1:in `new'
    from config.ru:1:in `<main>'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `eval'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `block in builder'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/bin/unicorn_rails:139:in `call'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/bin/unicorn_rails:139:in `block in rails_builder'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `call'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `build_app!'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:137:in `start'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/bin/unicorn_rails:209:in `<top (required)>'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
    from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'
```

The result is a 502 error in browser.

**Comment by pedroluislopez** [comment]
Exists problem also with /var/local/git/.ssh/ folder, it needs:

```chown -R git:git /var/local/git/.ssh/```

**Comment by bfabio** [comment]
@drybjed I think this can be closed.
