### ISSUE TITLE
gitlab install with postgresql failed 

### ISSUE THREAD

**Issue by Gomez** [debops/ansible-gitlab#7]
I enabled postgres with `gitlab_database: 'postgresql'` this happend on db init:

```
I, [2015-02-10T11:11:14.439024 #10021]  INFO -- : Refreshing Gem list
/var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `initialize': FATAL:  no pg_hba.conf entry for host "[local]", user "git", database "gitlabhq_production", SSL off (PG::Error)
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `new'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `connect'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:568:in `initialize'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `new'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:41:in `postgresql_connection'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:435:in `new_connection'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:445:in `checkout_new_connection'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `acquire_connection'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
        from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
        from /usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_handling.rb:87:in `connection'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/model_schema.rb:209:in `table_exists?'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/acts-as-taggable-on-2.4.1/lib/acts_as_taggable_on/acts_as_taggable_on/cache.rb:5:in `included'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/acts-as-taggable-on-2.4.1/lib/acts_as_taggable_on/taggable.rb:98:in `include'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/acts-as-taggable-on-2.4.1/lib/acts_as_taggable_on/taggable.rb:98:in `taggable_on'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/acts-as-taggable-on-2.4.1/lib/acts_as_taggable_on/taggable.rb:39:in `acts_as_taggable_on'
        from /var/local/git/gitlab/app/models/project.rb:45:in `<class:Project>'
        from /var/local/git/gitlab/app/models/project.rb:29:in `<top (required)>'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:348:in `require_or_load'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:480:in `load_missing_constant'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:180:in `const_missing'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:512:in `load_missing_constant'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:180:in `const_missing'
        from /var/local/git/gitlab/app/models/forked_project_link.rb:13:in `<class:ForkedProjectLink>'
        from /var/local/git/gitlab/app/models/forked_project_link.rb:12:in `<top (required)>'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `block in require'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:247:in `require'
        from /var/local/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/dependencies.rb:348:in `require_or_load'
```

The gitlab user does not have rights for the /etc/postgresql/9.1/main/pg_hba.conf. 

I am not a postgresql admin, was just a test.

**Comment by drybjed** [comment]
Thanks for the bug report! Default `pg_hba.conf` should probably be tweaked to allow system users to connect to a database with the same name if it's present. Otherwise, PostgreSQL deployment will get complicated since we either need to handle modification of `pg_hba.conf` in Ansible local facts, to that `debops.postgresql` role can pick that up, or... I don't know what. :-)

Anyway, database deployment from application roles is due to an overhaul. I'm thinking of changing it so that administrator will setup whichever database he wants (so that leaves configuration of the database to its respective role), and application role like `debops.gitlab` will try to pick the correct database if it finds one, or fail gracefully with a notification to the admin about required database. This also opens up a way to have databases on remote hosts.

**Comment by tracphil** [comment]
Databases on remote hosts would be really really sweet. Especially PostgreSQL ;)

**Comment by drybjed** [comment]
@tracphil I'm working on a generalized method how to do this properly. It will probably involve `stunnel`, because MySQL SSL support leaves a lot to be desired. I haven't looked into PostgreSQL yet.

**Comment by drybjed** [comment]
The involved PostgreSQL and GitLab roles have been redesigned, this issue is no longer relevant.
